# -*- coding: utf-8 -*-
"""Eesha Rizwan - STAT/CS 312 - Pre-Laboratory Activity A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19RlgzMzBL-Mq-4-ofIViJLcBPlKxDnbA

&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;


# Laboratory Lecture A #

Today is our first laboratory activity. I designed it to give you an introduction to using a notebook-style IDE. Google Colab is the online Python environment you should use for the course. You can also use Jupyter notebooks, but it will become rather cumbersome quickly (speed issues).

By the end of this lab, you should be able to work with Colab, have a better understanding of the structure of laboratory activities in this course, and understand the importance of preparation. Note that this laboratory activity is much more structured than most. In the future, these labs will contain less instruction, relying on your learning to that point (or on your Google skills).

&nbsp;
&nbsp;
&nbsp;

## Preamble ##

In this section, you import all of the necessary packages for the notebook. It is always good to have a separate section at the head to import packages. This is a part of proper programming presentation. If people expect the packages to be imported at the start, that is where you should place them.
"""

import math
import io
import os

import numpy as np
import pandas as pd
import statistics as stats
import scipy.stats as ss
import seaborn as sns
import matplotlib.pyplot as plt

"""## Data ##

Similarly, it is important to have the data loaded near the top of the script... for the same reason. If you use multiple data sets, then they should all be loaded at the top.

And... if you creating new data sets from the old ones (such as here), then you will want to do them in this section, too. Structure helps you to remember where you did things in your script.

### Import the data ###

If you are using Google Colab, the following cell is needed. It connects the notebook to your Google Drive. If you are using Jupyter notebooks, then this cell is (probably) not needed.
"""

### Note
#   If you are using Google Colab, the following cell is needed. It connects this notebook
#   to your Google Drive. If you are using Jupyter notebooks, then this cell is (probably)
#   not needed. You just need to ensure that the xlsx file is in the folder.


from google.colab import drive
drive.mount('/content/drive', force_remount=True)

pathname = "/content/drive/My Drive/STAT 312/Laboratory Activity A/"
os.chdir(pathname)

### Now, we load the datafile
#

filename = "RuralAtlasData24.xlsx"
dtP = pd.read_excel(filename, sheet_name="Income")

dtP

counties = dtP.loc[ dtP["FIPS"]/1000!=round(dtP["FIPS"]/1000) ]
counties

dtP.columns

"""### Descriptive Statistics ###"""

column_name = counties['Deep_Pov_All']
deep_poverty_data = column_name.dropna()

ss.describe(deep_poverty_data)

ss.variation(deep_poverty_data)

stats.median(deep_poverty_data)

ss.tstd(deep_poverty_data)

"""### Histogram ###"""

plt.hist(deep_poverty_data)
plt.title('Histogram of Percent of Residents in Deep Poverty')
plt.xlabel('Percent of Residents in Deep Poverty')
plt.ylabel('Frequency')

"""# Correlation"""

deep_pov_children = counties['Deep_Pov_Children'].dropna()
deep_pov_all = counties['Deep_Pov_All'].dropna()
correlation_coefficient= ss.spearmanr(deep_pov_children, deep_pov_all)
print (correlation_coefficient)

plt.figure(figsize=(10, 6))
plt.scatter(deep_pov_children, deep_pov_all, linewidth=0.5)
plt.title('Scatter Plot: Deep Poverty in Residents vs. Children')
plt.xlabel('Percent of Children in Deep Poverty')
plt.ylabel('Percent of Residents in Deep Poverty')
plt.show()

"""&nbsp;
&nbsp;
&nbsp;

## Regression ##

Finally, let us look at summarizing the relationship between two numeric variables using ordinary least squares (OLS) regression. This is the same regression you were introduced to in STAT 200. It is also the same regression that served as the basis for STAT 225.

In this function, the x-variable goes **first** (just as it did with the scatter plot).
"""

ss.linregress(deep_pov_children,deep_pov_all)

mod = ss.linregress(deep_pov_children,deep_pov_all)
mod

plt.figure(figsize=(8, 8))

plt.plot(deep_pov_children,deep_pov_all, 'o', label='The Data', c='#000080')

plt.plot(deep_pov_children, mod.intercept + mod.slope*deep_pov_children, c='#800000', label='OLS Line')

plt.title('Scatter Plot: Deep Poverty in Residents vs. Children')
plt.xlabel('Percent of Children in Deep Poverty')
plt.ylabel('Percent of Residents in Deep Poverty')
plt.show()

z= mod.slope *10 + mod.intercept
print (z)

"""&nbsp;
&nbsp;
&nbsp;

# The End #

This is the end of the direct-instruction part of this laboratory activity.

### Reference ###

```
@misc{RuralAtlasData23,
  title        = "Atlas of Rural and Small-Town {A}merica",
  author       = "{US Economic Research Service}",
  howpublished = "\url{https://www.ers.usda.gov/data-products/atlas-of-rural-and-small-town-america/download-the-data/}",
  year         = 2021,
  note         = "Accessed: 2021-06-08"
}
```
"""